Correct engines declaration
medikoo/memoizee pull request #138
Opened 2024-05-23 23:46 UTC by aredridel

2024-05-23 23:47 UTC, aredridel commented
Whoops, this duplicates #137 more or less — I'm not sure which is correct, 12 or 0.12

2024-05-24 01:35 UTC, BlakeEddie commented
https://github.com/medikoo/memoizee/pull/137 seems likely to be correct not really sure

2024-05-24 04:47 UTC, quochung-bic approved these changes

2024-05-24 07:52 UTC, medikoo requested changes
@aredridel thanks for the effort, still this one actually breaks syntax

2024-05-24 07:52 UTC, medikoo commented on package.json
> -	},
This change should not be here

2024-05-24 08:10 UTC, closed without merging

2024-05-24 14:47 UTC, aredridel commented on package.json
> -	},
Ah, sorry about that! Fat fingered using github's web editor.

2024-05-24 15:32 UTC, medikoo commented on package.json
> -	},
No worries, change in other line was good. Anyway I've pushed it on my own and it's released now.

Again, thanks for helping on that